spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dockerdb?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
    username: springstudent
    password: springstudent
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update



